# Generated by Django 4.2.7 on 2023-12-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom', to='customer.customer'),
        ),
    ]
